import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, join, relative } from "node:path";
import { udlClauseVocabulary } from "@hyperscale0/udl";
import { hsxDiagnostics } from "../../src/diagnostics.ts";
import { HSX_TYPE_KINDS } from "../../src/ir.ts";
import { KEYWORDS, PUNCT } from "../../src/lex.ts";
import { HSX_VERSION } from "../../src/version.ts";
import { USAGE_TEXT } from "../../src/cli.ts";

const packageRoot = join(import.meta.dir, "../..");
const generatedNote = `Generated by scripts/docs/build.ts for HSX ${HSX_VERSION}. Do not edit.`;
const generatedHeader = `<!-- ${generatedNote} -->\n\n`;

interface ModuleReference {
  readonly actions: readonly {
    readonly clauses: readonly string[];
    readonly name: string;
  }[];
  readonly name: string;
  readonly parameters: readonly string[];
  readonly ports: readonly string[];
  readonly source: string;
  readonly typeParameters: readonly string[];
}

function write(path: string, contents: string): void {
  mkdirSync(join(path, ".."), { recursive: true });
  const formatted = path.endsWith(".md")
    ? formatMarkdown(contents)
    : path.endsWith(".json")
      ? formatJson(contents)
      : contents;
  writeFileSync(path, formatted.endsWith("\n") ? formatted : `${formatted}\n`);
}

function formatJson(contents: string): string {
  return contents.replace(
    /^(\s*"[^"]+": )\[\n((?:\s+(?:"(?:\\.|[^"\\])*"|-?\d+(?:\.\d+)?|true|false|null),?\n)+)\s*\]/gm,
    (block, prefix: string, rows: string) => {
      const compact = `${prefix}[${rows
        .trim()
        .split("\n")
        .map((row) => row.trim().replace(/,$/, ""))
        .join(", ")}]`;
      return compact.length <= 80 ? compact : block;
    },
  );
}

function formatMarkdown(contents: string): string {
  const lines = contents.split("\n").map((line) => line.trimEnd());
  for (let start = 0; start < lines.length; start += 1) {
    if (!lines[start]?.startsWith("|") || !lines[start + 1]?.startsWith("|"))
      continue;
    let end = start;
    while (lines[end]?.startsWith("|")) end += 1;
    const rows = lines.slice(start, end).map((line) =>
      line
        .slice(1, -1)
        .split("|")
        .map((cell) => cell.trim()),
    );
    if (!rows[1]?.every((cell) => /^-+$/.test(cell))) continue;
    const widths = rows[0]?.map((_, column) =>
      Math.max(3, ...rows.map((row) => row[column]?.length ?? 0)),
    );
    if (!widths) continue;
    const formatted = rows.map(
      (row, rowIndex) =>
        `| ${widths
          .map((width, column) =>
            rowIndex === 1
              ? "-".repeat(width)
              : (row[column] ?? "").padEnd(width),
          )
          .join(" | ")} |`,
    );
    lines.splice(start, end - start, ...formatted);
    start += formatted.length - 1;
  }
  return lines.join("\n");
}

function splitTopLevel(value: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let start = 0;
  for (let index = 0; index < value.length; index += 1) {
    const char = value[index];
    if (char === "<" || char === "(" || char === "{" || char === "[")
      depth += 1;
    if (char === ">" || char === ")" || char === "}" || char === "]")
      depth -= 1;
    if (char === "," && depth === 0) {
      parts.push(value.slice(start, index).trim());
      start = index + 1;
    }
  }
  const tail = value.slice(start).trim();
  if (tail) parts.push(tail);
  return parts;
}

function matchingBrace(source: string, open: number): number {
  let depth = 0;
  let quoted = false;
  for (let index = open; index < source.length; index += 1) {
    const char = source[index];
    if (char === '"') quoted = !quoted;
    if (quoted) continue;
    if (char === "{") depth += 1;
    if (char === "}") {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  return source.length;
}

function clauseKeys(): readonly {
  readonly key: string;
  readonly spelling: string;
}[] {
  return udlClauseVocabulary.map((clause) => ({
    key: clause.target.replace(
      /[A-Z]/g,
      (letter) => `_${letter.toLowerCase()}`,
    ),
    spelling: clause.spelling,
  }));
}

function readModules(): ModuleReference[] {
  const root = join(packageRoot, "std", "settlements");
  return readdirSync(root)
    .filter((file) => file.endsWith(".hsx") && file !== "index.hsx")
    .sort()
    .map((file) => {
      const source = readFileSync(join(root, file), "utf8");
      const declaration =
        /export\s+instrument\s+([a-z][a-z0-9_]*)(?:<([^>]*)>)?\(([^)]*)\)/.exec(
          source,
        );
      if (!declaration?.[1])
        throw new Error(`${file} has no exported instrument`);
      const parameters = splitTopLevel(declaration[3] ?? "");
      const actions = [
        ...source.matchAll(
          /\baction\s+(?:\[([^\]]+)\]|([A-Za-z][A-Za-z0-9_]*))\s*\{/g,
        ),
      ].map((match) => {
        const open = (match.index ?? 0) + match[0].lastIndexOf("{");
        const body = source.slice(open + 1, matchingBrace(source, open));
        return {
          clauses: [
            ...new Set(
              clauseKeys()
                .filter(({ key }) => new RegExp(`\\b${key}\\s*[:{]`).test(body))
                .map(({ spelling }) => spelling),
            ),
          ].sort(),
          name: match[1] ?? match[2] ?? "action",
        };
      });
      return {
        actions,
        name: declaration[1],
        parameters,
        ports: parameters
          .filter((parameter) => /:\s*(?:optional<)?condition/.test(parameter))
          .map((parameter) => parameter.split(":")[0]?.trim() ?? parameter),
        source,
        typeParameters: splitTopLevel(declaration[2] ?? ""),
      };
    });
}

function diagnosticsMarkdown(): string {
  const sections = hsxDiagnostics.map((diagnostic) => {
    const example = diagnostic.example
      ? `\n\n\`\`\`hsx expect=${diagnostic.code}\n${diagnostic.example}\n\`\`\``
      : `\n\nNo source-only witness exists. ${diagnostic.reason ?? "The compiler host or lowering input must supply the invalid value."}`;
    return `## ${diagnostic.code}: ${diagnostic.title}\n\nStage: \`${diagnostic.stage}\`\n\nFix: ${diagnostic.fix}${example}`;
  });
  return `${generatedHeader}# Diagnostics\n\nUse \`hsx explain HSX####\` for the same catalog entry.\n\n${sections.join("\n\n")}\n`;
}

function grammarMarkdown(modules: readonly ModuleReference[]): string {
  const clauses = udlClauseVocabulary
    .map(({ spelling }) => `\`${spelling}\``)
    .join(", ");
  return `${generatedHeader}# Grammar vocabulary\n\nThe parser is hand-written. This page records the exported lexer vocabulary, the UDL clause vocabulary it binds, and the current standard-library module names.\n\n## Keywords\n\n${KEYWORDS.map((word) => `\`${word}\``).join(", ")}\n\n## Punctuation\n\n${PUNCT.map((mark) => `\`${mark}\``).join(", ")} and \`->\`\n\n## Typed clause spellings\n\n${clauses}\n\n## Standard-library modules\n\n${modules.map(({ name }) => `- \`${name}\``).join("\n")}\n`;
}

const typeNotes: Readonly<Record<(typeof HSX_TYPE_KINDS)[number], string>> = {
  account: "A currency-indexed ledger account reference.",
  boolean: "A compile-time or stored true or false value.",
  bps: "An integer basis-point value.",
  condition: "A declared decision port.",
  date: "A stored date-time string checked by UDL.",
  integer: "A bounded whole number.",
  money: "A currency-indexed minor-unit amount.",
  party: "A declared program party.",
  percent: "An exact percentage with basis-point precision.",
  ref: "A typed reference to another instrument.",
  text: "A finite string value.",
  unknown:
    "An internal checker result that source must resolve before lowering.",
};

function typesMarkdown(): string {
  const rows = HSX_TYPE_KINDS.map(
    (kind) => `| \`${kind}\` | ${typeNotes[kind]} |`,
  ).join("\n");
  return `${generatedHeader}# Types\n\nHSX checks types before it emits UDL. Money and account values carry a currency parameter, and no implicit currency conversion exists.\n\n| Kind | Meaning |\n| --- | --- |\n${rows}\n`;
}

function stdMarkdown(module: ModuleReference): string {
  const actions = module.actions.length
    ? module.actions
        .map(
          (action) =>
            `| \`${action.name}\` | ${action.clauses.map((clause) => `\`${clause}\``).join(", ") || "No typed action clause"} |`,
        )
        .join("\n")
    : "| None | None |";
  return `${generatedHeader}# ${module.name}\n\nSource: [\`std/settlements/${module.name}.hsx\`](../../../std/settlements/${module.name}.hsx)\n\n## Export\n\n\`${module.name}${module.typeParameters.length ? `<${module.typeParameters.join(", ")}>` : ""}\`\n\n## Parameters\n\n${module.parameters.map((parameter) => `- \`${parameter}\``).join("\n") || "None."}\n\n## Decision ports\n\n${module.ports.map((port) => `- \`${port}\``).join("\n") || "None."}\n\n## Actions and clauses\n\n| Action | Clauses lowered |\n| --- | --- |\n${actions}\n`;
}

function udlOutputMarkdown(): string {
  return `${generatedHeader}# UDL output\n\nAn accepted compile returns three artifacts.\n\n| Artifact | Contents |\n| --- | --- |\n| \`document\` | The canonical UDL object. Serialize it with \`serializeUdl\` from \`@hyperscale0/udl\`. |\n| \`originMap\` | Canonical UDL paths mapped to authored HSX spans. |\n| \`costManifest\` | The deterministic manifest pinned to the supplied rate card. |\n\nCanonical UDL sorts object keys, preserves array order, uses two-space JSON indentation, and ends with one line feed.\n`;
}

function editorGrammar(modules: readonly ModuleReference[]): string {
  const words = (values: readonly string[]) => `\\b(?:${values.join("|")})\\b`;
  return `${JSON.stringify(
    {
      $schema:
        "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
      fileTypes: ["hsx"],
      name: "HSX",
      patterns: [
        { include: "#comments" },
        { include: "#strings" },
        { include: "#percents" },
        { include: "#numbers" },
        { include: "#keywords" },
        { include: "#clauses" },
        { include: "#modules" },
        { include: "#punctuation" },
      ],
      repository: {
        clauses: {
          match: words(
            udlClauseVocabulary.map(({ spelling }) =>
              spelling.replaceAll(" ", "_"),
            ),
          ),
          name: "support.function.clause.hsx",
        },
        comments: { match: "//.*$", name: "comment.line.double-slash.hsx" },
        keywords: { match: words(KEYWORDS), name: "keyword.control.hsx" },
        modules: {
          match: words(modules.map(({ name }) => name)),
          name: "support.class.module.hsx",
        },
        numbers: {
          match: "\\b[0-9]+(?:\\.[0-9]+)?\\b",
          name: "constant.numeric.hsx",
        },
        percents: {
          match: "\\b[0-9]+(?:\\.[0-9]+)?%",
          name: "constant.numeric.percentage.hsx",
        },
        punctuation: {
          match: "(?:->|[{}()\\[\\]:,;=|.<>?])",
          name: "punctuation.hsx",
        },
        strings: { match: '"[^"\\n]*"', name: "string.quoted.double.hsx" },
      },
      scopeName: "source.hsx",
    },
    null,
    2,
  )}\n`;
}

function snippets(modules: readonly ModuleReference[]): string {
  return `${JSON.stringify(
    Object.fromEntries(
      modules.map((module) => [
        module.name,
        {
          body: [
            `settlement \${1:name} = ${module.name} {`,
            ...module.parameters
              .filter((parameter) => !parameter.includes("optional<"))
              .map(
                (parameter, index) =>
                  `  ${parameter.split(":")[0]?.trim()}: \${${index + 2}:value}`,
              ),
            "}",
          ],
          description: `Apply the ${module.name} standard-library module.`,
          prefix: module.name,
        },
      ]),
    ),
    null,
    2,
  )}\n`;
}

function shortMap(modules: readonly ModuleReference[]): string {
  return `${generatedHeader}# HSX documentation\n\n> Repository guide and generated compiler reference for HSX ${HSX_VERSION}.\n\n## Guide\n\n${guideFiles()
    .map(
      (file) =>
        `[${titleOf(join(packageRoot, "docs", "guide", file))}](guide/${file}): Hand-written chapter with compiler-checked programs.`,
    )
    .join(
      "\n",
    )}\n\n## Reference\n\n[Grammar](reference/grammar.md): Lexer, clause, and module vocabulary.\n[Types](reference/types.md): HSX type kinds.\n[Diagnostics](reference/diagnostics.md): Stable HSX diagnostic codes and fixes.\n[CLI](reference/cli.md): Generated command usage.\n[UDL output](reference/udl-output.md): Compile artifacts and canonical output.\n${modules.map(({ name }) => `[${name}](reference/std/${name}.md): Standard-library module.`).join("\n")}\n`;
}

function guideFiles(): string[] {
  return readdirSync(join(packageRoot, "docs", "guide"))
    .filter((file) => file.endsWith(".md"))
    .sort();
}

function titleOf(path: string): string {
  return (
    /^#\s+(.+)$/m.exec(readFileSync(path, "utf8"))?.[1] ?? basename(path, ".md")
  );
}

export function buildDocs(outputRoot = packageRoot): readonly string[] {
  const modules = readModules();
  const docsRoot = join(outputRoot, "docs");
  const stdRoot = join(docsRoot, "reference", "std");
  rmSync(stdRoot, { force: true, recursive: true });
  const outputs: string[] = [];
  const emit = (path: string, contents: string) => {
    write(join(outputRoot, path), contents);
    outputs.push(path);
  };
  emit("docs/reference/diagnostics.md", diagnosticsMarkdown());
  emit("docs/reference/grammar.md", grammarMarkdown(modules));
  emit("docs/reference/types.md", typesMarkdown());
  emit(
    "docs/reference/cli.md",
    `${generatedHeader}# CLI\n\n\`\`\`text\n${USAGE_TEXT}\n\`\`\`\n`,
  );
  emit("docs/reference/udl-output.md", udlOutputMarkdown());
  for (const module of modules)
    emit(`docs/reference/std/${module.name}.md`, stdMarkdown(module));
  emit("docs/llms.txt", shortMap(modules));
  const readingOrder = [
    ...guideFiles().map((file) => join(packageRoot, "docs", "guide", file)),
    ...outputs
      .filter((path) => path.startsWith("docs/reference/"))
      .map((path) => join(outputRoot, path))
      .sort(),
  ];
  emit(
    "docs/llms-full.txt",
    `${generatedHeader}# HSX full documentation\n\n${readingOrder
      .map((path) =>
        readFileSync(path, "utf8")
          .replace(/^<!-- Generated[^\n]*-->\n\n/, "")
          .trim(),
      )
      .join("\n\n")}\n`,
  );
  emit("editors/vscode/syntaxes/hsx.tmLanguage.json", editorGrammar(modules));
  emit("editors/vscode/snippets/hsx.json", snippets(modules));
  return outputs.map((path) => relative(outputRoot, join(outputRoot, path)));
}

if (import.meta.main) {
  buildDocs();
  console.log(`wrote HSX ${HSX_VERSION} documentation and editor goldens`);
}
