import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, join, relative } from "node:path";
import { udlClauseVocabulary } from "@hyperscale0/udl";
import { hsxDiagnostics } from "../../src/diagnostics.ts";
import { HSX_TYPE_KINDS } from "../../src/ir.ts";
import { KEYWORDS, PUNCT } from "../../src/lex.ts";
import { HSX_VERSION } from "../../src/version.ts";
import { USAGE_TEXT } from "../../src/cli.ts";
import { compile, parseProgram, type UdlCostTable } from "../../src/index.ts";
import type { BlockExpr, Entry } from "../../src/ast.ts";

const packageRoot = join(import.meta.dir, "../..");
const generatedNote = `Generated by scripts/docs/build.ts for HSX ${HSX_VERSION}. Do not edit.`;
const generatedHeader = `<!-- ${generatedNote} -->\n\n`;

interface ModuleReference {
  readonly actions: readonly {
    readonly clauses: readonly string[];
    readonly name: string;
  }[];
  readonly clauses: readonly string[];
  readonly name: string;
  readonly parameters: readonly string[];
  readonly ports: readonly string[];
  readonly source: string;
  readonly typeParameters: readonly string[];
}

function write(path: string, contents: string): void {
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, contents.endsWith("\n") ? contents : `${contents}\n`);
}

function blockEntries(block: BlockExpr): Entry[] {
  return block.entries.flatMap((entry) => [
    entry,
    ...(entry.value.kind === "block" ? blockEntries(entry.value) : []),
  ]);
}

function clausesIn(entries: readonly Entry[]): string[] {
  const keys = new Set(entries.map((entry) => entry.key.name));
  return [
    ...new Set(
      udlClauseVocabulary
        .filter((clause) =>
          [
            clause.spelling,
            clause.spelling.replaceAll(" ", "_"),
            clause.target,
            clause.target.replace(
              /[A-Z]/g,
              (letter) => `_${letter.toLowerCase()}`,
            ),
          ].some((key) => keys.has(key)),
        )
        .map((clause) => clause.spelling),
    ),
  ].sort();
}

function readModules(): ModuleReference[] {
  const root = join(packageRoot, "std", "money_flows");
  return readdirSync(root)
    .filter((file) => file.endsWith(".hsx") && file !== "index.hsx")
    .sort()
    .map((file) => {
      const source = readFileSync(join(root, file), "utf8");
      const parsed = parseProgram(source);
      if (parsed.diagnostics.length)
        throw new Error(`${file}: ${JSON.stringify(parsed.diagnostics)}`);
      const declaration = parsed.program.decls.find(
        (decl) => decl.kind === "instrument" && decl.exported,
      );
      if (!declaration || declaration.kind !== "instrument")
        throw new Error(`${file} has no exported instrument`);
      const parameters = declaration.parameters.map((parameter) =>
        source.slice(parameter.span.start, parameter.span.end),
      );
      const entries = parsed.program.decls.flatMap((decl) =>
        decl.kind === "instrument" ? blockEntries(decl.body) : [],
      );
      const actions = entries
        .filter(
          (entry) =>
            entry.key.name === "action" && entry.value.kind === "block",
        )
        .map((entry) => ({
          name: entry.qualifiers.map((name) => name.name).join(" "),
          clauses: clausesIn(
            entry.value.kind === "block" ? blockEntries(entry.value) : [],
          ),
        }));
      return {
        actions,
        clauses: clausesIn(entries),
        name: declaration.name.name,
        parameters,
        ports: parameters
          .filter((parameter) => /:\s*(?:optional<)?condition/.test(parameter))
          .map((parameter) => parameter.split(":")[0]?.trim() ?? parameter),
        source,
        typeParameters: declaration.typeParameters.map(
          (parameter) => parameter.name.name,
        ),
      };
    });
}

function moduleGuidance(source: string): string {
  return source
    .slice(0, source.indexOf("export instrument"))
    .split("\n")
    .filter((line) => line.startsWith("//"))
    .map((line) => line.replace(/^\/\/ ?/, ""))
    .join("\n")
    .trim()
    .replace(/(?<!\n)\n(#+ .*)$/gm, "\n\n$1")
    .replace(/^(#+ .*)\n(?!\n)/gm, "$1\n\n");
}

function parameterTable(module: ModuleReference): string {
  const notes = new Map<string, string>();
  let name: string | undefined;
  for (const line of module.source.split("\n")) {
    const item = /^\/\/ - `([^`]+)`: (.*)$/.exec(line);
    if (item) {
      name = item[1]!;
      if (!notes.has(name)) notes.set(name, item[2]!);
    } else if (name && /^\/\/   \S/.test(line)) {
      notes.set(name, `${notes.get(name)} ${line.slice(5).trim()}`);
    } else name = undefined;
  }
  const rows = module.parameters.map((parameter) => {
    const colon = parameter.indexOf(":");
    const name = parameter.slice(0, colon).trim();
    const type = parameter.slice(colon + 1).trim();
    const guidance =
      notes.get(name) ??
      moduleGuidance(module.source)
        .replace(/```[\s\S]*?```/g, "")
        .replace(/^#+ .*$/gm, "")
        .replaceAll("\n", " ")
        .split(/(?<=[.!?])\s+/)
        .find((sentence) => new RegExp(`\\b${name}\\b`).test(sentence));
    if (!guidance)
      throw new Error(`${module.name}.${name} has no parameter guidance`);
    const note = guidance.replaceAll("\n", " ").replaceAll("|", "&#124;");
    return `| \`${name}\` | \`${type}\` | ${type.startsWith("optional<") ? "No" : "Yes"} | ${note} |`;
  });
  return `| Parameter | Type | Required | Meaning |\n| --- | --- | --- | --- |\n${rows.join("\n")}`;
}

export function checkGuideExamples(): void {
  const costTable = JSON.parse(
    readFileSync(join(packageRoot, "examples/cost-table.json"), "utf8"),
  ) as UdlCostTable[];
  for (const file of guideFiles()) {
    const text = readFileSync(join(packageRoot, "docs/guide", file), "utf8");
    for (const match of text.matchAll(
      /```hsx source=(examples\/[^\s]+)\n([\s\S]*?)```/g,
    )) {
      const source = readFileSync(join(packageRoot, match[1]!), "utf8");
      if (source !== match[2])
        throw new Error(`${file}: example differs from ${match[1]}`);
      const result = compile(source, { costTable });
      if (!result.artifacts || result.diagnostics.length)
        throw new Error(`${match[1]}: ${JSON.stringify(result.diagnostics)}`);
    }
  }
}

function diagnosticsMarkdown(): string {
  const sections = hsxDiagnostics.map((diagnostic) => {
    const example = diagnostic.example
      ? `\n\n\`\`\`hsx expect=${diagnostic.code}\n${diagnostic.example}\n\`\`\``
      : `\n\nNo source-only witness exists. ${diagnostic.reason ?? "The compiler host or lowering input must supply the invalid value."}`;
    return `## ${diagnostic.code}: ${diagnostic.title}\n\nStage: \`${diagnostic.stage}\`\n\nFix: ${diagnostic.fix}${example}`;
  });
  return `${generatedHeader}# Diagnostics\n\nUse \`hsx explain HSX####\` for the same catalog entry.\n\n${sections.join("\n\n")}\n`;
}

function grammarMarkdown(modules: readonly ModuleReference[]): string {
  const clauses = udlClauseVocabulary
    .map(({ spelling }) => `\`${spelling}\``)
    .join(", ");
  return `${generatedHeader}# Grammar vocabulary\n\nThe parser is hand-written. This page records the exported lexer vocabulary, the UDL clause vocabulary it binds, and the current standard-library module names.\n\n## Keywords\n\n${KEYWORDS.map((word) => `\`${word}\``).join(", ")}\n\n## Punctuation\n\n${PUNCT.map((mark) => `\`${mark}\``).join(", ")} and \`->\`\n\n## Typed clause spellings\n\n${clauses}\n\n## Standard-library modules\n\n${modules.map(({ name }) => `- \`${name}\``).join("\n")}\n`;
}

const typeNotes: Readonly<Record<(typeof HSX_TYPE_KINDS)[number], string>> = {
  account: "A currency-indexed ledger account reference.",
  boolean: "A compile-time or stored true or false value.",
  bps: "An integer basis-point value.",
  condition: "A declared decision port.",
  date: "A stored date-time string checked by UDL.",
  integer: "A bounded whole number.",
  money: "A currency-indexed minor-unit amount.",
  party: "A declared program party.",
  percent: "An exact percentage with basis-point precision.",
  ref: "A typed reference to another instrument.",
  text: "A finite string value.",
  unknown:
    "An internal checker result that source must resolve before lowering.",
};

function typesMarkdown(): string {
  const rows = HSX_TYPE_KINDS.map(
    (kind) => `| \`${kind}\` | ${typeNotes[kind]} |`,
  ).join("\n");
  const accountFields = readFileSync(
    join(packageRoot, "docs/guide/03-instruments.md"),
    "utf8",
  )
    .split("## Account fields\n")[1]!
    .split("\n## ")[0]!
    .trim();
  return `${generatedHeader}# Types\n\nHSX checks types before it emits UDL. Money and account values carry a currency parameter, and no implicit currency conversion exists.\n\n| Kind | Meaning |\n| --- | --- |\n${rows}\n\n## Account fields\n\n${accountFields}\n`;
}

function stdMarkdown(module: ModuleReference): string {
  const actions = module.actions.length
    ? module.actions
        .map(
          (action) =>
            `| \`${action.name}\` | ${action.clauses.map((clause) => `\`${clause}\``).join(", ") || "No typed action clause"} |`,
        )
        .join("\n")
    : "| None | None |";
  return `${generatedHeader}# ${module.name}\n\nSource: [\`std/money_flows/${module.name}.hsx\`](../../../std/money_flows/${module.name}.hsx)\n\n## Export\n\n\`${module.name}${module.typeParameters.length ? `<${module.typeParameters.join(", ")}>` : ""}\`\n\n## Parameters\n\n${parameterTable(module)}\n\nRequired means required by the template signature. A selected mode may also need parameters marked optional; the guidance below describes those combinations.\n\n## Module guidance\n\n${moduleGuidance(module.source)}\n\n## Declared clauses\n\n${module.clauses.map((clause) => `- \`${clause}\``).join("\n")}\n\nThis inventory covers all branches and nested instruments in the module. The selected parameters determine which clauses and actions the compiler emits. Indexed action names expand over the declared finite list.\n\n## Decision ports\n\n${module.ports.map((port) => `- \`${port}\``).join("\n") || "None."}\n\n## Actions and clauses\n\n| Action | Clauses lowered |\n| --- | --- |\n${actions}\n`;
}

function udlOutputMarkdown(): string {
  return `${generatedHeader}# UDL output\n\nAn accepted compile returns three artifacts.\n\n| Artifact | Contents |\n| --- | --- |\n| \`document\` | The canonical UDL object. Serialize it with \`serializeUdl\` from \`@hyperscale0/udl\`. |\n| \`originMap\` | Canonical UDL paths mapped to authored HSX spans. |\n| \`costManifest\` | The deterministic manifest pinned to the supplied rate card. |\n\nCanonical UDL sorts object keys, preserves array order, uses two-space JSON indentation, and ends with one line feed.\n`;
}

function editorGrammar(modules: readonly ModuleReference[]): string {
  const words = (values: readonly string[]) => `\\b(?:${values.join("|")})\\b`;
  return `${JSON.stringify(
    {
      $schema:
        "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
      fileTypes: ["hsx"],
      name: "HSX",
      patterns: [
        { include: "#comments" },
        { include: "#strings" },
        { include: "#percents" },
        { include: "#numbers" },
        { include: "#keywords" },
        { include: "#clauses" },
        { include: "#modules" },
        { include: "#punctuation" },
      ],
      repository: {
        clauses: {
          match: words(
            udlClauseVocabulary.map(({ spelling }) =>
              spelling.replaceAll(" ", "_"),
            ),
          ),
          name: "support.function.clause.hsx",
        },
        comments: { match: "//.*$", name: "comment.line.double-slash.hsx" },
        keywords: { match: words(KEYWORDS), name: "keyword.control.hsx" },
        modules: {
          match: words(modules.map(({ name }) => name)),
          name: "support.class.module.hsx",
        },
        numbers: {
          match: "\\b[0-9]+(?:\\.[0-9]+)?\\b",
          name: "constant.numeric.hsx",
        },
        percents: {
          match: "\\b[0-9]+(?:\\.[0-9]+)?%",
          name: "constant.numeric.percentage.hsx",
        },
        punctuation: {
          match: "(?:->|[{}()\\[\\]:,;=|.<>?])",
          name: "punctuation.hsx",
        },
        strings: { match: '"[^"\\n]*"', name: "string.quoted.double.hsx" },
      },
      scopeName: "source.hsx",
    },
    null,
    2,
  )}\n`;
}

function snippets(modules: readonly ModuleReference[]): string {
  return `${JSON.stringify(
    Object.fromEntries(
      modules.map((module) => [
        module.name,
        {
          body: [
            `settlement \${1:name} = ${module.name} {`,
            ...module.parameters
              .filter((parameter) => !parameter.includes("optional<"))
              .map(
                (parameter, index) =>
                  `  ${parameter.split(":")[0]?.trim()}: \${${index + 2}:value}`,
              ),
            "}",
          ],
          description: `Apply the ${module.name} standard-library module.`,
          prefix: module.name,
        },
      ]),
    ),
    null,
    2,
  )}\n`;
}

function shortMap(modules: readonly ModuleReference[]): string {
  return `${generatedHeader}# HSX documentation\n\n> Repository guide and generated compiler reference for HSX ${HSX_VERSION}.\n\n## Guide\n\n${guideFiles()
    .map(
      (file) =>
        `[${titleOf(join(packageRoot, "docs", "guide", file))}](guide/${file}): Hand-written chapter with compiler-checked programs.`,
    )
    .join(
      "\n",
    )}\n\n## Reference\n\n[Grammar](reference/grammar.md): Lexer, clause, and module vocabulary.\n[Types](reference/types.md): HSX type kinds and account role pins.\n[Diagnostics](reference/diagnostics.md): Stable HSX diagnostic codes and fixes.\n[CLI](reference/cli.md): Generated command usage.\n[UDL output](reference/udl-output.md): Compile artifacts and canonical output.\n${modules.map(({ name }) => `[${name}](reference/std/${name}.md): Standard-library module.`).join("\n")}\n`;
}

function guideFiles(): string[] {
  return readdirSync(join(packageRoot, "docs", "guide"))
    .filter((file) => file.endsWith(".md"))
    .sort();
}

function titleOf(path: string): string {
  return (
    /^#\s+(.+)$/m.exec(readFileSync(path, "utf8"))?.[1] ?? basename(path, ".md")
  );
}

export function buildDocs(outputRoot = packageRoot): readonly string[] {
  checkGuideExamples();
  const modules = readModules();
  const docsRoot = join(outputRoot, "docs");
  const stdRoot = join(docsRoot, "reference", "std");
  rmSync(stdRoot, { force: true, recursive: true });
  const outputs: string[] = [];
  const emit = (path: string, contents: string) => {
    write(join(outputRoot, path), contents);
    outputs.push(path);
  };
  emit("docs/reference/diagnostics.md", diagnosticsMarkdown());
  emit("docs/reference/grammar.md", grammarMarkdown(modules));
  emit("docs/reference/types.md", typesMarkdown());
  emit(
    "docs/reference/cli.md",
    `${generatedHeader}# CLI\n\n\`\`\`text\n${USAGE_TEXT}\n\`\`\`\n`,
  );
  emit("docs/reference/udl-output.md", udlOutputMarkdown());
  for (const module of modules)
    emit(`docs/reference/std/${module.name}.md`, stdMarkdown(module));
  emit("docs/llms.txt", shortMap(modules));
  const readingOrder = [
    ...guideFiles().map((file) => join(packageRoot, "docs", "guide", file)),
    ...outputs
      .filter((path) => path.startsWith("docs/reference/"))
      .map((path) => join(outputRoot, path))
      .sort(),
  ];
  emit(
    "docs/llms-full.txt",
    `${generatedHeader}# HSX full documentation\n\n${readingOrder
      .map((path) =>
        readFileSync(path, "utf8")
          .replace(/^<!-- Generated[^\n]*-->\n\n/, "")
          .trim(),
      )
      .join("\n\n")}\n`,
  );
  emit("editors/vscode/syntaxes/hsx.tmLanguage.json", editorGrammar(modules));
  emit("editors/vscode/snippets/hsx.json", snippets(modules));
  return outputs.map((path) => relative(outputRoot, join(outputRoot, path)));
}

if (import.meta.main) {
  buildDocs();
  console.log(`wrote HSX ${HSX_VERSION} documentation and editor goldens`);
}
