import { spawnSync } from "node:child_process";
import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";
import { pathToFileURL } from "node:url";

const packageRoot = join(import.meta.dir, "..");
const monorepoRoot = join(packageRoot, "../..");
const examplesRoot = join(packageRoot, "examples");
const playgroundDir = join(packageRoot, "playground");
const examplesFile = join(playgroundDir, "examples.ts");
const distDir = join(playgroundDir, "dist");

function collectHsxFiles(dir: string): string[] {
  const entries = readdirSync(dir).sort();
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      files.push(...collectHsxFiles(full));
    } else if (stat.isFile() && entry.endsWith(".hsx")) {
      files.push(full);
    }
  }
  return files;
}

export function generateExamplesCode(): {
  readonly code: string;
  readonly count: number;
} {
  const files = collectHsxFiles(examplesRoot);
  const items: Array<{ name: string; source: string }> = [];

  for (const file of files) {
    const rel = relative(examplesRoot, file);
    const source = readFileSync(file, "utf8");
    items.push({ name: rel, source });
  }

  items.sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [
    "// Generated by open/hsx/scripts/build-playground.ts. Do not edit by hand.",
    "",
    "export interface PlaygroundExample {",
    "  readonly name: string;",
    "  readonly source: string;",
    "}",
    "",
    "export const PLAYGROUND_EXAMPLES: readonly PlaygroundExample[] = [",
  ];

  for (const item of items) {
    lines.push(
      "  {",
      `    name: ${JSON.stringify(item.name)},`,
      `    source: ${JSON.stringify(item.source)},`,
      "  },",
    );
  }

  lines.push("];", "");
  return {
    code: lines.join("\n"),
    count: items.length,
  };
}

export async function buildPlayground(check = false): Promise<void> {
  const { code: examplesCode, count } = generateExamplesCode();

  if (check) {
    let committedExamples: readonly {
      readonly name: string;
      readonly source: string;
    }[];
    try {
      const mod = (await import(pathToFileURL(examplesFile).href)) as {
        readonly PLAYGROUND_EXAMPLES: readonly {
          readonly name: string;
          readonly source: string;
        }[];
      };
      committedExamples = mod.PLAYGROUND_EXAMPLES;
    } catch (error) {
      console.error(
        `failed to import ${relative(packageRoot, examplesFile)}:`,
        error,
      );
      process.exit(1);
    }

    const committedMap = new Map(
      committedExamples.map((ex) => [ex.name, ex.source]),
    );
    const diskFiles = collectHsxFiles(examplesRoot);
    const diskMap = new Map<string, string>();
    for (const file of diskFiles) {
      diskMap.set(relative(examplesRoot, file), readFileSync(file, "utf8"));
    }

    const differences: string[] = [];
    for (const [rel, diskContent] of diskMap) {
      if (!committedMap.has(rel)) {
        differences.push(`added: ${rel}`);
      } else if (committedMap.get(rel) !== diskContent) {
        differences.push(`edited: ${rel}`);
      }
    }
    for (const rel of committedMap.keys()) {
      if (!diskMap.has(rel)) {
        differences.push(`deleted: ${rel}`);
      }
    }

    if (differences.length > 0) {
      console.error(
        "open/hsx/playground/examples.ts is out of sync with open/hsx/examples:",
      );
      for (const diff of differences.sort()) {
        console.error(`  ${diff}`);
      }
      process.exit(1);
    }
  } else {
    mkdirSync(playgroundDir, { recursive: true });
    writeFileSync(examplesFile, examplesCode, "utf8");
    spawnSync("bunx", ["vp", "fmt", examplesFile, "--write"], {
      cwd: monorepoRoot,
      stdio: "inherit",
    });
    console.log(`inlined ${count} examples into playground/examples.ts`);
  }

  mkdirSync(distDir, { recursive: true });

  const result = await Bun.build({
    entrypoints: [join(playgroundDir, "main.ts")],
    format: "esm",
    minify: false,
    naming: {
      entry: "[name].[ext]",
    },
    outdir: distDir,
    target: "browser",
  });

  if (!result.success) {
    for (const log of result.logs) {
      console.error(log);
    }
    throw new Error("Bun.build failed for playground");
  }

  copyFileSync(join(playgroundDir, "index.html"), join(distDir, "index.html"));
  copyFileSync(join(playgroundDir, "styles.css"), join(distDir, "styles.css"));
  console.log(`built playground into ${relative(packageRoot, distDir)}/`);

  if (check) {
    const distFiles = readdirSync(distDir);
    const violations: string[] = [];

    for (const fileName of distFiles) {
      const filePath = join(distDir, fileName);
      const stat = statSync(filePath);
      if (!stat.isFile()) continue;

      const content = readFileSync(filePath, "utf8");
      if (content.includes("node:")) {
        violations.push(`${fileName} contains "node:"`);
      }
      if (content.includes("import.meta.url")) {
        violations.push(`${fileName} contains "import.meta.url"`);
      }
    }

    if (violations.length > 0) {
      console.error(
        `playground:check failed. Disallowed tokens found in dist:\n${violations.join("\n")}`,
      );
      process.exit(1);
    }
    console.log(
      "playground:check passed: static bundle is free of node: and import.meta.url",
    );
  }
}

if (import.meta.main) {
  const isCheck = process.argv.includes("--check");
  await buildPlayground(isCheck);
}
