import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { parseProgram } from "../src/parse.ts";
import { scan } from "../src/lex.ts";
import type { HsxExample } from "../src/examples.ts";

const directory = new URL("../examples/", import.meta.url);

export function readExamples(): HsxExample[] {
  return readdirSync(directory)
    .filter((name) => name.endsWith(".hsx"))
    .sort()
    .map((name) => {
      const source = readFileSync(new URL(name, directory), "utf8");
      const parsed = parseProgram(source);
      if (
        parsed.diagnostics.length ||
        parsed.program.header ||
        !parsed.program.title
      )
        throw new Error(
          `${name}: expected a program with a display title; ${parsed.diagnostics.map((d) => d.message).join("; ")}`,
        );
      const comments: string[] = [];
      for (const token of scan(source).tokens) {
        if (token.kind !== "comment") break;
        comments.push(token.text.slice(2).trim());
      }
      const summary = comments.join(" ");
      if (!summary)
        throw new Error(`${name}: start with a // business summary`);
      return {
        id: name.slice(0, -4),
        title: parsed.program.title,
        summary,
        headers: parsed.program.decls
          .filter((d) => d.kind === "use")
          .map((d) => d.name),
        source,
      };
    });
}

export function generateExamplesBundleCode(): string {
  return [
    "// Generated by open/hsx/scripts/bundle-examples.ts. Do not edit by hand.",
    'import type { HsxExample } from "./examples.ts";',
    "export const examples: HsxExample[] = [",
    ...readExamples().map((example) => `  ${JSON.stringify(example)},`),
    "];",
    "",
  ].join("\n");
}

if (import.meta.main)
  writeFileSync(
    new URL("../src/examples-bundle.ts", import.meta.url),
    generateExamplesBundleCode(),
    "utf8",
  );
