import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const packageRoot = join(import.meta.dir, "..");
const stdRoot = join(packageRoot, "std");
const targetPath = join(packageRoot, "src", "std-bundle.ts");

function collectFiles(dir: string): string[] {
  const entries = readdirSync(dir).sort();
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      files.push(...collectFiles(full));
    } else if (stat.isFile()) {
      files.push(full);
    }
  }
  return files;
}

export function generateStdBundleCode(): {
  readonly code: string;
  readonly files: ReadonlyMap<string, string>;
} {
  const files = collectFiles(stdRoot);
  const fileMap = new Map<string, string>();
  for (const full of files) {
    const rel = relative(stdRoot, full);
    const content = readFileSync(full, "utf8");
    fileMap.set(rel, content);
  }

  const sortedKeys = [...fileMap.keys()].sort();
  const lines: string[] = [
    "// Generated by open/hsx/scripts/bundle-std.ts. Do not edit by hand.",
    "",
    "export const BUNDLED_STD_FILES: ReadonlyMap<string, string> = new Map<string, string>([",
  ];

  for (const key of sortedKeys) {
    const content = fileMap.get(key)!;
    lines.push(`  [${JSON.stringify(key)}, ${JSON.stringify(content)}],`);
  }

  lines.push("]);", "");
  return {
    code: lines.join("\n"),
    files: fileMap,
  };
}

if (import.meta.main) {
  writeFileSync(targetPath, generateStdBundleCode().code, "utf8");
}
