import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const packageRoot = join(import.meta.dir, "..");
const stdRoot = join(packageRoot, "std");
const targetPath = join(packageRoot, "src", "std-bundle.ts");

export function generateStdBundleCode(): {
  readonly code: string;
  readonly files: ReadonlyMap<string, string>;
} {
  const files = readdirSync(stdRoot)
    .filter((name) => name.endsWith(".hsx"))
    .sort()
    .map((name) => join(stdRoot, name));
  const fileMap = new Map<string, string>();
  for (const full of files) {
    const rel = relative(stdRoot, full);
    const content = readFileSync(full, "utf8");
    fileMap.set(rel, content);
  }

  const sortedKeys = [...fileMap.keys()].sort();
  const lines: string[] = [
    "// Generated by open/hsx/scripts/bundle-std.ts. Do not edit by hand.",
    "",
    "export const BUNDLED_STD_FILES: ReadonlyMap<string, string> = new Map<string, string>([",
  ];

  for (const key of sortedKeys) {
    const content = fileMap.get(key)!;
    lines.push(`  [${JSON.stringify(key)}, ${JSON.stringify(content)}],`);
  }

  lines.push("]);", "");
  return {
    code: lines.join("\n"),
    files: fileMap,
  };
}

if (import.meta.main) {
  writeFileSync(targetPath, generateStdBundleCode().code, "utf8");
}
