import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { parseProgram } from "../src/parse.ts";
import { scan } from "../src/lex.ts";
import type { HsxBase } from "../src/bases.ts";

const directory = new URL("../bases/", import.meta.url);

export function readBases(): HsxBase[] {
  return readdirSync(directory)
    .filter((name) => name.endsWith(".hsx"))
    .sort()
    .map((name) => {
      const source = readFileSync(new URL(name, directory), "utf8");
      const parsed = parseProgram(source);
      if (
        parsed.diagnostics.length ||
        parsed.program.header ||
        !parsed.program.title
      )
        throw new Error(
          `${name}: expected a program with a display title; ${parsed.diagnostics.map((d) => d.message).join("; ")}`,
        );
      const comments: string[] = [];
      for (const token of scan(source).tokens) {
        if (token.kind !== "comment") break;
        comments.push(token.text.slice(2).trim());
      }
      const summary = comments.join(" ");
      if (!summary)
        throw new Error(`${name}: start with a // mechanism summary`);
      return {
        id: name.slice(0, -4),
        title: parsed.program.title,
        summary,
        headers: parsed.program.decls
          .filter((d) => d.kind === "use")
          .map((d) => d.name),
        source,
      };
    });
}

export function generateBasesBundleCode(): string {
  return [
    "// Generated by open/hsx/scripts/bundle-bases.ts. Do not edit by hand.",
    'import type { HsxBase } from "./bases.ts";',
    "export const bases: HsxBase[] = [",
    ...readBases().map((base) => `  ${JSON.stringify(base)},`),
    "];",
    "",
  ].join("\n");
}

if (import.meta.main)
  writeFileSync(
    new URL("../src/bases-bundle.ts", import.meta.url),
    generateBasesBundleCode(),
    "utf8",
  );
