/**
 * Settlement declarations shared by checking and lowering. A local event cap
 * limits one settlement before the whole-program budget applies.
 */

export const SETTLEMENT_ARCHETYPES = [
  "advance",
  "captured_payment",
  "conditional_disbursement",
  "credit_facility",
  "deposit",
  "funding_round",
  "held_payment",
  "instant_transfer",
  "metered",
  "pooled_split",
  "premium_forward",
  "recurring_collection",
  "rotating_pool",
  "scheduled",
  "settlement_batch",
  "swap",
  "weighted_distribution",
] as const;

export type ArchetypeName = (typeof SETTLEMENT_ARCHETYPES)[number];

interface ArchetypeDefinition {
  readonly eventCap: number;
  readonly keys: readonly string[];
  readonly maxRates?: number;
  readonly maxRecipients?: number;
  readonly referenceableExits: readonly string[];
  readonly required: readonly string[];
}

export const ARCHETYPE_DEFINITIONS: Record<ArchetypeName, ArchetypeDefinition> =
  {
    advance: {
      eventCap: 2,
      keys: [
        "against",
        "amount",
        "count",
        "every",
        "fee",
        "first_due",
        "funder",
        "to",
      ],
      referenceableExits: [],
      // The repayment source is one of two shapes, so the advance checker states
      // that requirement instead of listing either shape's keys as required.
      required: ["funder", "to", "amount"],
    },
    captured_payment: {
      eventCap: 4,
      keys: [
        "amount",
        "capture_mode",
        "correction",
        "correction_mode",
        "external_reversal",
        "fees",
        "negative_position",
        "payee",
        "payer",
        "reserve_until",
        "timeout",
      ],
      referenceableExits: [],
      required: [
        "payer",
        "payee",
        "amount",
        "capture_mode",
        "reserve_until",
        "correction",
        "external_reversal",
        "correction_mode",
        "negative_position",
        "timeout",
      ],
    },
    conditional_disbursement: {
      eventCap: 1,
      keys: [
        "amount",
        "cap",
        "decision",
        "destination",
        "recovery_policy",
        "reopen_policy",
        "source",
      ],
      referenceableExits: [],
      required: [
        "source",
        "destination",
        "cap",
        "amount",
        "decision",
        "reopen_policy",
        "recovery_policy",
      ],
    },
    credit_facility: {
      eventCap: 1,
      keys: [
        "availability_policy",
        "borrower",
        "close_policy",
        "draw_destination",
        "expires_at",
        "expiry_policy",
        "lender",
        "limit",
        "obligation",
      ],
      referenceableExits: [],
      required: [
        "lender",
        "borrower",
        "draw_destination",
        "limit",
        "expires_at",
        "obligation",
        "availability_policy",
        "expiry_policy",
        "close_policy",
      ],
    },
    deposit: {
      eventCap: 1,
      keys: ["amount", "claim", "holder", "payer", "return"],
      referenceableExits: [],
      required: ["payer", "holder", "amount", "claim", "return"],
    },
    funding_round: {
      eventCap: 4,
      keys: [
        "beneficiary",
        "cancel_policy",
        "close_by",
        "close_policy",
        "commitment",
        "contributor",
        "fail_policy",
        "max_contributors",
        "overfund_policy",
        "target",
      ],
      referenceableExits: [],
      required: [
        "contributor",
        "beneficiary",
        "target",
        "commitment",
        "max_contributors",
        "close_by",
        "close_policy",
        "overfund_policy",
        "cancel_policy",
        "fail_policy",
      ],
    },
    held_payment: {
      eventCap: 7,
      keys: ["amount", "fees", "on_cancel", "payer", "payee", "release"],
      referenceableExits: ["release"],
      required: ["payer", "payee", "amount", "release"],
    },
    instant_transfer: {
      eventCap: 3,
      keys: ["amount", "fees", "payer", "payee"],
      referenceableExits: [],
      required: ["payer", "payee", "amount"],
    },
    metered: {
      eventCap: 14,
      keys: ["close_by", "payer", "payee", "rates"],
      maxRates: 14,
      referenceableExits: [],
      required: ["payer", "payee", "rates", "close_by"],
    },
    pooled_split: {
      eventCap: 14,
      keys: ["amount", "payer", "payout_due", "split"],
      maxRecipients: 7,
      referenceableExits: [],
      required: ["payer", "amount", "split", "payout_due"],
    },
    premium_forward: {
      eventCap: 6,
      keys: [
        "amount",
        "bind",
        "carrier",
        "commission",
        "endorsement",
        "endorsement_policy",
        "lapse_policy",
        "on_cancel",
        "payer",
        "policy_ref",
        "renewal_due",
        "renewal_policy",
      ],
      referenceableExits: [],
      required: ["payer", "carrier", "amount", "bind"],
    },
    recurring_collection: {
      eventCap: 0,
      keys: [
        "attempt_policy",
        "failure_policy",
        "mandate",
        "obligation",
        "period_idempotency",
        "retry_policy",
      ],
      referenceableExits: [],
      required: [
        "obligation",
        "mandate",
        "attempt_policy",
        "period_idempotency",
        "retry_policy",
        "failure_policy",
      ],
    },
    rotating_pool: {
      eventCap: 3,
      keys: [
        "contribution",
        "count",
        "default_policy",
        "every",
        "exit_policy",
        "first_due",
        "guarantee_policy",
        "guarantor",
        "members",
        "payout_order",
      ],
      referenceableExits: [],
      required: [
        "members",
        "contribution",
        "count",
        "every",
        "first_due",
        "payout_order",
        "default_policy",
        "guarantee_policy",
        "exit_policy",
      ],
    },
    scheduled: {
      eventCap: 3,
      keys: [
        "advance_to",
        "amount",
        "count",
        "debtor",
        "delinquency_policy",
        "every",
        "first_due",
        "mode",
        "partial_payment",
        "payer",
        "payee",
        "refund_policy",
        "repayment_matching",
        "reschedule_policy",
      ],
      referenceableExits: ["obligation"],
      required: ["payer", "payee", "amount", "count", "every", "first_due"],
    },
    settlement_batch: {
      eventCap: 1,
      keys: [
        "close_trigger",
        "external_reversal_offsets",
        "fee_entries",
        "negative_position",
        "payout_destination",
        "payout_acknowledgement",
        "payout_beneficiary_ref",
        "settlement_account",
        "source_capture_refs",
      ],
      referenceableExits: [],
      required: [
        "settlement_account",
        "source_capture_refs",
        "fee_entries",
        "external_reversal_offsets",
        "close_trigger",
        "payout_destination",
        "negative_position",
        "payout_acknowledgement",
        "payout_beneficiary_ref",
      ],
    },
    swap: {
      eventCap: 10,
      keys: ["amounts", "between", "dispute", "fees", "release"],
      referenceableExits: [],
      required: ["between", "amounts", "release"],
    },
    weighted_distribution: {
      eventCap: 1,
      keys: [
        "amount",
        "correction_policy",
        "max_recipients",
        "recipient",
        "record_at",
        "rounding_policy",
        "snapshot",
        "source",
        "weight",
        "withholding_policy",
      ],
      referenceableExits: [],
      required: [
        "source",
        "recipient",
        "amount",
        "weight",
        "max_recipients",
        "record_at",
        "snapshot",
        "rounding_policy",
        "withholding_policy",
        "correction_policy",
      ],
    },
  };
